const SCHEMA_TELEGRAM = {
  id: "channels",
  titleKey: "section.channels.title",
  descKey: "section.channels.desc",
  stepKey: "stepTelegram",
  fields: [
    {
      key: "channels.telegram.enabled",
      labelKey: "field.tgEnable.label",
      helpKey: "field.tgEnable.help",
      type: "toggle",
    },
    {
      key: "_tg_guide",
      type: "guide",
      titleKey: "tg.guide.title",
      steps: ["tg.guide.step1", "tg.guide.step2", "tg.guide.step3", "tg.guide.step4"],
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.allowFrom",
      labelKey: "field.tgUserId.label",
      helpKey: "field.tgUserId.help",
      placeholderKey: "field.tgUserId.placeholder",
      type: "multi-text",
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.botToken",
      labelKey: "field.tgToken.label",
      helpKey: "field.tgToken.help",
      placeholderKey: "field.tgToken.placeholder",
      type: "password",
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.dmPolicy",
      labelKey: "field.tgDm.label",
      helpKey: "field.tgDm.help",
      type: "select",
      options: [
        { value: "pairing", labelKey: "opt.pairing" },
        { value: "open", labelKey: "opt.open" },
        { value: "allowlist", labelKey: "opt.allowlist" },
        { value: "disabled", labelKey: "opt.disabled" },
      ],
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.groupPolicy",
      labelKey: "field.tgGroup.label",
      helpKey: "field.tgGroup.help",
      type: "select",
      options: [
        { value: "allowlist", labelKey: "opt.group-allowlist" },
        { value: "open", labelKey: "opt.group-open" },
        { value: "disabled", labelKey: "opt.group-disabled" },
      ],
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.groups.requireMention",
      labelKey: "field.tgMention.label",
      helpKey: "field.tgMention.help",
      type: "toggle",
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.replyToMode",
      labelKey: "field.tgReplyTo.label",
      helpKey: "field.tgReplyTo.help",
      type: "select",
      options: [
        { value: "first", labelKey: "opt.replyFirst" },
        { value: "all", labelKey: "opt.replyAll" },
        { value: "off", labelKey: "opt.replyOff" },
      ],
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.linkPreview",
      labelKey: "field.tgLinkPreview.label",
      helpKey: "field.tgLinkPreview.help",
      type: "toggle",
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.streamMode",
      labelKey: "field.tgStream.label",
      helpKey: "field.tgStream.help",
      type: "select",
      options: [
        { value: "partial", labelKey: "opt.streamPartial" },
        { value: "block", labelKey: "opt.streamBlock" },
        { value: "off", labelKey: "opt.streamOff" },
      ],
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
    {
      key: "channels.telegram.historyLimit",
      labelKey: "field.tgHistory.label",
      helpKey: "field.tgHistory.help",
      type: "select",
      options: [
        { value: 25, labelKey: "opt.history25" },
        { value: 50, labelKey: "opt.history50" },
        { value: 100, labelKey: "opt.history100" },
      ],
      showWhen: { key: "channels.telegram.enabled", value: true },
    },
  ],
};
